/*
 * Copyright (C) 2026  David Darras
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

static const char* BALL_NAMES[] = {
    "None", // 0
    "Master Ball", // 1
    "Ultra Ball", // 2
    "Great Ball", // 3
    "Poké Ball", // 4
    "Safari Ball", // 5
    "Net Ball", // 6
    "Dive Ball", // 7
    "Nest Ball", // 8
    "Repeat Ball", // 9
    "Timer Ball", // 10
    "Luxury Ball", // 11
    "Premier Ball", // 12
    "Dusk Ball", // 13
    "Heal Ball", // 14
    "Quick Ball", // 15
    "Cherish Ball", // 16
    "Speed Ball", // 17
    "Level Ball", // 18
    "Lure Ball", // 19
    "Heavy Ball", // 20
    "Love Ball", // 21
    "Friend Ball", // 22
    "Moon Ball", // 23
    "Sport Ball", // 24
    "Dream Ball" // 25
};

static const size_t BALL_COUNT = SIZE(BALL_NAMES);
