/*
 * Copyright (C) 2026  David Darras
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

static const char* NATURE_NAMES[] = {
    "Hardy", // 0
    "Lonely", // 1
    "Brave", // 2
    "Adamant", // 3
    "Naughty", // 4
    "Bold", // 5
    "Docile", // 6
    "Relaxed", // 7
    "Impish", // 8
    "Lax", // 9
    "Timid", // 10
    "Hasty", // 11
    "Serious", // 12
    "Jolly", // 13
    "Naive", // 14
    "Modest", // 15
    "Mild", // 16
    "Quiet", // 17
    "Bashful", // 18
    "Rash", // 19
    "Calm", // 20
    "Gentle", // 21
    "Sassy", // 22
    "Careful", // 23
    "Quirky" // 24
};

static const size_t NATURE_COUNT = SIZE(NATURE_NAMES);
