/*
 * Copyright (C) 2026  David Darras
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * @file decoration.h
 * @brief The ids of the Secret Base decorations.
 */

#pragma once

#include <types.h>

namespace overworld {

/// The id of a Secret Base decoration. See overworld::PlacedDecorations.
enum class DecorationId : u16 {
  kSmallDesk = 0,
  kPokeBallDesk = 1,
  kHeavyDesk = 2,
  kRoughDesk = 3,
  kSoftDesk = 4,
  kElegantDesk = 5,
  kBrickDesk = 6,
  kLogDesk = 7,
  kHardDesk = 8,
  kIcyDesk = 9,
  kSmallChair = 10,
  kPokeBallChair = 11,
  kHeavyChair = 12,
  kElegantChair = 13,
  kSoftChair = 14,
  kRoughChair = 15,
  kBrickChair = 16,
  kLogChair = 17,
  kHardChair = 18,
  kWelcomeMat1 = 19,
  kWelcomeMat2 = 20,
  kWelcomeMat3 = 21,
  kWelcomeMat4 = 22,
  kWelcomeMat5 = 23,
  kSurfMat = 24,
  kThunderMat = 25,
  kFireBlastMat = 26,
  kPowderSnowMat = 27,
  kAttractMat = 28,
  kFissureMat = 29,
  kSpikesMat = 30,
  kGreenMat = 31,
  kRedMat = 32,
  kBlueMat = 33,
  kFlatMat = 34,
  kRedFlower = 35,
  kTropicalPlant = 36,
  kFloweringPlant = 37,
  kColorfulPlant = 38,
  kBigPlant = 39,
  kElegantBonsai = 40,
  kBerryTree = 41,
  kRedBrick = 42,
  kYellowBrick = 43,
  kBlueBrick = 44,
  kSandOrnament = 45,
  kGymStatue = 46,
  kComfortableBed = 47,
  kFence = 48,
  kSlide = 49,
  kStand = 50,
  kTire = 51,
  kSolidBoard = 52,
  kStairs = 53,
  kMakiwara = 54,
  kBoppoyama = 55,
  kProclamation = 56,
  kBlackboard = 57,
  kConfettiBall = 58,
  kCandlestick = 59,
  kPokeFlute = 60,
  kBerryBlender = 61,
  kGlobe = 62,
  kCardboardBoxes = 63,
  kTrashCan = 64,
  kStandingStone = 65,
  kGlassOrnament = 66,
  kStarLight = 67,
  kMeditativeSeat = 68,
  kHeterarchicalLoop = 69,
  kRedTent = 70,
  kBlueTent = 71,
  kMiniCastelia = 72,
  kMiniLumiose = 73,
  kPokeBallPoster = 74,
  kGreenPoster = 75,
  kRedPoster = 76,
  kBluePoster = 77,
  kCutePoster = 78,
  kPikaPoster = 79,
  kLongPoster = 80,
  kSeaPoster = 81,
  kSkyPoster = 82,
  kKissPoster = 83,
  kRedScroll = 84,
  kBlueScroll = 85,
  kGreenScroll = 86,
  kDadsScroll = 87,
  kParadoxicalPopper = 88,
  kRegionalAward = 89,
  kNationalAward = 90,
  kTimeTravelAward = 91,
  kPichuDoll = 92,
  kPikachuDoll = 93,
  kMarillDoll = 94,
  kTogepiDoll = 95,
  kCyndaquilDoll = 96,
  kChikoritaDoll = 97,
  kTotodileDoll = 98,
  kJigglypuffDoll = 99,
  kMeowthDoll = 100,
  kClefairyDoll = 101,
  kDittoDoll = 102,
  kSmoochumDoll = 103,
  kTreeckoDoll = 104,
  kTorchicDoll = 105,
  kMudkipDoll = 106,
  kDuskullDoll = 107,
  kWynautDoll = 108,
  kBaltoyDoll = 109,
  kKecleonDoll = 110,
  kAzurillDoll = 111,
  kSkittyDoll = 112,
  kSwabluDoll = 113,
  kGulpinDoll = 114,
  kLotadDoll = 115,
  kSeedotDoll = 116,
  kSubstituteDoll = 117,
  kSnorlaxDoll = 118,
  kRhydonDoll = 119,
  kLaprasDoll = 120,
  kVenusaurDoll = 121,
  kCharizardDoll = 122,
  kBlastoiseDoll = 123,
  kWailmerDoll = 124,
  kRegiceDoll = 125,
  kRegirockDoll = 126,
  kRegisteelDoll = 127,
  kPokeBallCushion = 128,
  kPikaCushion = 129,
  kRoundCushion = 130,
  kKissCushion = 131,
  kZigzagCushion = 132,
  kSpinCushion = 133,
  kDiamondCushion = 134,
  kGrassCushion = 135,
  kFireCushion = 136,
  kWaterCushion = 137,
  kTv = 138,
  kRoundTv = 139,
  kCuteTv = 140,
  kWornOutLight = 141,
  kMoodLighting = 142,
  kJukebox = 143,
  kVendingMachine = 144,
  kLevelRelease = 145,
  kRedBalloon = 146,
  kYellowBalloon = 147,
  kBlueBalloon = 148,
  kMudBall = 149,
  kBreakableDoor = 150,
  kTallGrass = 151,
  kInvisibleDoll = 152,
  kGlitterMat = 153,
  kJumpMat = 154,
  kSpinMat = 155,
  kPitfallMat = 156,
  kSquareOneMat = 157,
  kLowCNoteMat = 158,
  kDNoteMat = 159,
  kENoteMat = 160,
  kFNoteMat = 161,
  kGNoteMat = 162,
  kANoteMat = 163,
  kBNoteMat = 164,
  kHighCNoteMat = 165,
  kRedSpinPanel = 166,
  kBlueSpinPanel = 167,
  kYellowSpinPanel = 168,
  kRedWarpPanel = 169,
  kBlueWarpPanel = 170,
  kYellowWarpPanel = 171,
  kToyPc = 172,
  kYourLocation = 173,

  kCount = 174,
};

} // namespace overworld
