/*
 * Copyright (C) 2026  David Darras
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include "core/types.h"

namespace battle {

enum class AnimationStepKind : u16 {
  kSectionPokemon = 0,
  kPokemonTeleport = 1,
  kPokemonShift = 2,
  kPokemonGlideToPokemon = 3,
  kPokemonResetPosition = 4,
  kPokemonGlideToModel = 5,
  kPokemonSpin = 6,
  kPokemonFacePokemon = 7,
  kPokemonResize = 8,
  kPokemonShow = 9,
  kPokemonShowNonTargets = 10,
  kPokemonShowShadow = 11,
  kPokemonPlayPose = 12,
  kPokemonPlayAttackPose = 13,
  kPokemonPoseSpeed = 14,
  kPokemonOutline = 15,
  kPokemonTint = 16,
  kPokemonFollowModel = 17,
  kPokemonStopShake = 18,
  kPokemonShake = 19,
  kSectionCamera = 20,
  kCameraJump = 21,
  kCameraShift = 22,
  kCameraGlideToPokemon = 23,
  kCameraLock = 24,
  kCameraOrbitPokemon = 25,
  kCameraRestore = 26,
  kCameraDepth = 27,
  kCameraTurn = 28,
  kCameraTurnToPokemon = 29,
  kCameraRumble = 30,
  kCameraClipOnPokemon = 31,
  kCameraClipOnPosition = 32,
  kCameraClipFollow = 33,
  kCameraClipEnd = 34,
  kCameraClipPlanes = 35,
  kCameraClipPlanesScreen = 36,
  kCameraScreenDepthEffect = 37,
  kCameraFlatView = 38,
  kCameraClipRotate = 39,
  kCameraClipScale = 40,
  kCameraClipMirror = 41,
  kSectionEffect = 42,
  kEffectSpawn = 43,
  kEffectStopEmitting = 44,
  kEffectTeleport = 45,
  kEffectShift = 46,
  kEffectGlideToPokemon = 47,
  kEffectGlideToPokemonRotated = 48,
  kEffectGlideToFieldPoint = 49,
  kEffectOrbitPokemon = 50,
  kEffectGlideToModel = 51,
  kEffectResize = 52,
  kEffectTurn = 53,
  kEffectTurnToPokemon = 54,
  kEffectFollowCamera = 55,
  kEffectFollowModel = 56,
  kEffectFollowPokemon = 57,
  kEffectLockDisplay = 58,
  kEffectAutoSpin = 59,
  kEffectStopShake = 60,
  kEffectShake = 61,
  kSectionModel = 62,
  kModelSpawn = 63,
  kModelSpawnBall = 64,
  kModelTeleport = 65,
  kModelShift = 66,
  kModelGlideToPokemon = 67,
  kModelGlideToPokemonRotated = 68,
  kModelGlideToFieldPoint = 69,
  kModelOrbitPokemon = 70,
  kModelTurn = 71,
  kModelTurnToPokemon = 72,
  kModelResize = 73,
  kModelShow = 74,
  kModelStickToCamera = 75,
  kModelStickToModel = 76,
  kModelFollowPokemon = 77,
  kModelAutoSpin = 78,
  kModelTint = 79,
  kModelPlayMotion = 80,
  kModelSwitchMotion = 81,
  kModelPlayTextureAnimation = 82,
  kModelPlayVisibilityAnimation = 83,
  kModelPlayShaderAnimation = 84,
  kModelMotionSpeed = 85,
  kModelLightDirection = 86,
  kModelBallLightDirection = 87,
  kModelStopShake = 88,
  kModelShake = 89,
  kModelLockDisplay = 90,
  kModelReplaceTexture = 91,
  kSectionSound = 92,
  kSoundPlay = 93,
  kSoundVolume = 94,
  kSoundPan = 95,
  kSoundPitch = 96,
  kSoundTempo = 97,
  kSoundPlayCry = 98,
  kSound3dSetup = 99,
  kSound3dPlay = 100,
  kSound3dStop = 101,
  kSound3dTeleport = 102,
  kSound3dShift = 103,
  kSound3dGlideToPokemon = 104,
  kSound3dFollowPokemon = 105,
  kSound3dFollowObject = 106,
  kSound3dGlideToFieldPoint = 107,
  kSound3dPlayCry = 108,
  kSectionDisplay = 109,
  kHealthBarShow = 110,
  kHealthBarShowAll = 111,
  kHealthBarApplyDamage = 112,
  kHealthBarApplyDamageAll = 113,
  kKnockbackFlag = 114,
  kBreakObjectsFlag = 115,
  kSectionBackdrop = 116,
  kBackdropColorToggle = 117,
  kBackdropColor = 118,
  kBackdropShow = 119,
  kScreenFadeIn = 120,
  kScreenFadeOut = 121,
  kSectionDebris = 122,
  kDebrisSpawn = 123,
  kDebrisTeleport = 124,
  kDebrisShift = 125,
  kDebrisGlideToPokemon = 126,
  kDebrisGlideToFieldPoint = 127,
  kDebrisTurn = 128,
  kDebrisResize = 129,
  kDebrisSpread = 130,
  kDebrisVelocity = 131,
  kDebrisGravity = 132,
  kDebrisInitialSize = 133,
  kDebrisInitialTurn = 134,
  kDebrisSizeCurve = 135,
  kDebrisTurnCurve = 136,
  kDebrisMaterialAnimation = 137,
  kDebrisModelAnimation = 138,
  kDebrisReflection = 139,
  kSectionSpecial = 140,
  kChainAttackSetup = 141,
  kMegaEvolution = 142,
  kChargeHide = 143,
  kSubstituteShow = 144,
  kAegislashFormChange = 145,
  kWeatherChange = 146,
  kFieldEffectStart = 147,
  kFieldEffectEnd = 148,
  kPlatformControl = 149,
  kSectionTrainer = 150,
  kTrainerTeleport = 151,
  kTrainerTurn = 152,
  kTrainerTurnToPokemon = 153,
  kTrainerShow = 154,
  kTrainerPlayPose = 155,
  kTrainerPoseSpeed = 156,
  kTrainerShowBallGauge = 157,
  kTrainerTint = 158,
  kSectionOverlay = 159,
  kOverlayCreate = 160,
  kOverlayDelete = 161,
  kOverlayAnimationStart = 162,
  kOverlayAnimationStop = 163,
  kOverlayAnimationSpeed = 164,
  kOverlayAnimationFrame = 165,
  kOverlayDarken = 166,
  kOverlayBrighten = 167,
  kOverlayTrainerPicture = 168,
  kOverlayText = 169,
  kOverlayDepth = 170,
  kSectionContest = 171,
  kEffectSpawnForContest = 172,
  kInputWindow = 173,
  kPokemonTeleportQuad = 174,
  kPokemonTintQuad = 175,
  kPokemonSpinQuad = 176,
  kCameraClipOnPokemonQuad = 177,
  kCameraGlideToPokemonQuad = 178,
  kEffectGlideToPokemonQuad = 179,
  kModelGlideToPokemonQuad = 180,
  kPokemonHappyPose = 181,
  kOverlayTrainerPictureAndText = 182,
  kSoundPlayCryQuad = 183,
  kPokemonShowQuad = 184,
  kSubstituteVisibility = 185,
  kPokemonSkyPose = 186,
  kOverlayTextContest = 187,
  kSectionTest = 188,
  kPokemonShadeEffect = 189,
  kPokemonPointLight = 190,
  kPokemonGazeAt = 191,
  kMessageShow = 192,
  kMessageDismiss = 193,
  kModelRemove = 194,
  kEffectDelete = 195,
  kModelResetSize = 196,
  kModelArc = 197,
  kCameraClipScaleValue = 198,
  kWaitForAnimation = 199,
  kSound3dTest = 200,
  kPlatformShow = 201,
  kDebugSwapPokemon = 202,
  kDebugProbe = 203,
  kSectionLegacy = 204,
  kEffectGlideToPokemonLegacy = 205,
  kEffectGlideToPokemonRotatedLegacy = 206,
  kPokemonPlayPoseDirect = 207,
  kPokemonShowSpecial = 208,
  kPokemonWildCry = 209,
  kPokemonResetAll = 210,
  kPlaceholder = 211,
  kNote = 212,
};

constexpr u32 kAnimationStepKindCount = 213;

}
