/*
 * Copyright (C) 2026  David Darras
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

static const c8* STATIC_ENCOUNTER_NAMES[] = {
    "Poochyena", // 0
    "Thundurus", // 1
    "Tornadus", // 2
    "Landorus", // 3
    "Dialga", // 4
    "Palkia", // 5
    "Giratina", // 6
    "Entei", // 7
    "Raikou", // 8
    "Suicune", // 9
    "Terrakion", // 10
    "Cobalion", // 11
    "Virizion", // 12
    "Uxie", // 13
    "Azelf", // 14
    "Mesprit", // 15
    "Reshiram", // 16
    "Zekrom", // 17
    "Kyurem", // 18
    "HoOh", // 19
    "Lugia", // 20
    "Voltorb1", // 21
    "Voltorb2", // 22
    "Voltorb3", // 23
    "Voltorb4", // 24
    "Spiritomb", // 25
    "Kyogre", // 26
    "Groudon", // 27
    "Rayquaza", // 28
    "Deoxys1", // 29
    "Taillow", // 30
    "Wingull", // 31
    "Pelipper", // 32
    "Swablu", // 33
    "Braviary", // 34
    "Drifblim", // 35
    "Murkrow", // 36
    "Heatran", // 37
    "Cresselia", // 38
    "Kecleon1", // 39
    "Kecleon2", // 40
    "Kecleon3", // 41
    "Kecleon4", // 42
    "Kecleon5", // 43
    "Kecleon6", // 44
    "Electrode1", // 45
    "Electrode2", // 46
    "Electrode3", // 47
    "Electrode4", // 48
    "KyogrePrimal", // 49
    "GroudonPrimal", // 50
    "Regirock", // 51
    "Regice", // 52
    "Registeel", // 53
    "Regigigas", // 54
    "Wurmple", // 55
    "Latios", // 56
    "Latias", // 57
    "Deoxys2", // 58
};