/*
 * Copyright (C) 2026  David Darras
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#define BATTLE_GROUND_NONE                  (0)
#define BATTLE_GROUND_GRASS                 (1)
#define BATTLE_GROUND_FACTORY               (2)
#define BATTLE_GROUND_CAVE                  (3)
#define BATTLE_GROUND_FOREST                (4)
#define BATTLE_GROUND_SHORE                 (5)
#define BATTLE_GROUND_MOUNTAIN              (6)
#define BATTLE_GROUND_INDOORS               (7)
#define BATTLE_GROUND_CITY                  (8)
#define BATTLE_GROUND_TOWN                  (9)
#define BATTLE_GROUND_PALACE                (10)
#define BATTLE_GROUND_COMMUNICATION         (11)
#define BATTLE_GROUND_WATER                 (12)
#define BATTLE_GROUND_SEA                   (13)
#define BATTLE_GROUND_SNOW_CAVE             (14)
#define BATTLE_GROUND_MIRROR_DUNGEON        (15)
#define BATTLE_GROUND_ROCK_GYM_LEADER       (16)
#define BATTLE_GROUND_FIGHTING_GYM_LEADER   (17)
#define BATTLE_GROUND_ELECTRIC_GYM_LEADER   (18)
#define BATTLE_GROUND_FIRE_GYM_LEADER       (19)
#define BATTLE_GROUND_NORMAL_GYM_LEADER     (20)
#define BATTLE_GROUND_FLYING_GYM_LEADER     (21)
#define BATTLE_GROUND_PSYCHIC_GYM_LEADER    (22)
#define BATTLE_GROUND_WATER_GYM_LEADER      (23)
#define BATTLE_GROUND_ELITE_FOUR_DARK       (24)
#define BATTLE_GROUND_ELITE_FOUR_ICE        (25)
#define BATTLE_GROUND_ELITE_FOUR_GHOST      (26)
#define BATTLE_GROUND_ELITE_FOUR_DRAGON     (27)
#define BATTLE_GROUND_CHAMPION_BATTLE       (28)
#define BATTLE_GROUND_DARK_ROOM             (29)
#define BATTLE_GROUND_WCS                   (30)
#define BATTLE_GROUND_WCS_2                 (31)
#define BATTLE_GROUND_ROCK_GYM_LEADER_2     (32)
#define BATTLE_GROUND_FIGHTING_GYM_LEADER_2 (33)
#define BATTLE_GROUND_ELECTRIC_GYM_LEADER_2 (34)
#define BATTLE_GROUND_FIRE_GYM_LEADER_2     (35)
#define BATTLE_GROUND_NORMAL_GYM_LEADER_2   (36)
#define BATTLE_GROUND_FLYING_GYM_LEADER_2   (37)
#define BATTLE_GROUND_PSYCHIC_GYM_LEADER_2  (38)
#define BATTLE_GROUND_WATER_GYM_LEADER_2    (39)
#define BATTLE_GROUND_SKY_BATTLE            (40)
#define BATTLE_GROUND_WATER_CAVE            (41)
#define BATTLE_GROUND_GREY                  (42)
#define BATTLE_GROUND_DESERT                (43)
#define BATTLE_GROUND_VOLCANIC              (44)
#define BATTLE_GROUND_CITY_SHORE            (45)
#define BATTLE_GROUND_FORD                  (46)
#define BATTLE_GROUND_CITY_FORD             (47)
#define BATTLE_GROUND_SEABED                (48)
#define BATTLE_GROUND_STONE_CAVE            (49)
#define BATTLE_GROUND_WATERFALL_CAVE        (50)
#define BATTLE_GROUND_SEABED_CAVE           (51)
#define BATTLE_GROUND_WATERFALL             (52)
#define BATTLE_GROUND_UNDERSEA_AQUA_HIDEOUT (53)
#define BATTLE_GROUND_CYCLING               (54)
#define BATTLE_GROUND_SHIP                  (55)
#define BATTLE_GROUND_CEMETERY              (56)
#define BATTLE_GROUND_SKY_PILLAR            (57)
#define BATTLE_GROUND_POKEMON_RUBY          (58)
#define BATTLE_GROUND_POKEMON_SAPPHIRE      (59)
#define BATTLE_GROUND_POKEMON_EMERALD       (60)
#define BATTLE_GROUND_POKEMON_LEGENDARY     (61)
#define BATTLE_GROUND_CONTEST_A_COOL        (62)
#define BATTLE_GROUND_CONTEST_A_BEAUTIFUL   (63)
#define BATTLE_GROUND_CONTEST_A_CUTE        (64)
#define BATTLE_GROUND_CONTEST_A_CLEVER      (65)
#define BATTLE_GROUND_CONTEST_A_STRONG      (66)
#define BATTLE_GROUND_CONTEST_B_COOL        (67)
#define BATTLE_GROUND_CONTEST_B_BEAUTIFUL   (68)
#define BATTLE_GROUND_CONTEST_B_CUTE        (69)
#define BATTLE_GROUND_CONTEST_B_CLEVER      (70)
#define BATTLE_GROUND_CONTEST_B_STRONG      (71)
#define BATTLE_GROUND_CONTEST_C_COOL        (72)
#define BATTLE_GROUND_CONTEST_C_BEAUTIFUL   (73)
#define BATTLE_GROUND_CONTEST_C_CUTE        (74)
#define BATTLE_GROUND_CONTEST_C_CLEVER      (75)
#define BATTLE_GROUND_CONTEST_C_STRONG      (76)
#define BATTLE_GROUND_CONTEST_D_COOL        (77)
#define BATTLE_GROUND_CONTEST_D_BEAUTIFUL   (78)
#define BATTLE_GROUND_CONTEST_D_CUTE        (79)
#define BATTLE_GROUND_CONTEST_D_CLEVER      (80)
#define BATTLE_GROUND_CONTEST_D_STRONG      (81)
#define BATTLE_GROUND_CONTEST_OPENING       (82)
#define BATTLE_GROUND_CONTEST_ENDING        (83)
#define BATTLE_GROUND_AQUA_BOSS             (84)
#define BATTLE_GROUND_MAGMA_BOSS            (85)
#define BATTLE_GROUND_SKY_PILLAR_TOP        (86)
#define BATTLE_GROUND_DEOXYS                (87)
#define BATTLE_GROUND_VOLCANO               (88)
#define BATTLE_GROUND_VICTORY_ROAD          (89)
#define BATTLE_GROUND_ALL_NIGHT_EVENT       (90)
#define BATTLE_GROUND_AQUA_HIDEOUT_CAVE     (91)
#define BATTLE_GROUND_ABANDONED_SHIP        (92)
