/*
 * Copyright (C) 2026  David Darras
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#define FORM_VENUSAUR_NORMAL (0)
#define FORM_VENUSAUR_MEGA (1)
#define FORM_VENUSAUR_COUNT (2)

#define FORM_CHARIZARD_NORMAL (0)
#define FORM_CHARIZARD_MEGAX (1)
#define FORM_CHARIZARD_MEGAY (2)
#define FORM_CHARIZARD_COUNT (3)

#define FORM_BLASTOISE_NORMAL (0)
#define FORM_BLASTOISE_MEGA (1)
#define FORM_BLASTOISE_COUNT (2)

#define FORM_BEEDRILL_NORMAL (0)
#define FORM_BEEDRILL_MEGA (1)
#define FORM_BEEDRILL_COUNT (2)

#define FORM_PIDGEOT_NORMAL (0)
#define FORM_PIDGEOT_MEGA (1)
#define FORM_PIDGEOT_COUNT (2)

#define FORM_PIKACHU_NORMAL (0)
#define FORM_PIKACHU_STYLE (1)
#define FORM_PIKACHU_BEAUTIFUL (2)
#define FORM_PIKACHU_CUTE (3)
#define FORM_PIKACHU_CLEVER (4)
#define FORM_PIKACHU_STRONG (5)
#define FORM_PIKACHU_CONTEST (6)
#define FORM_PIKACHU_COUNT (7)

#define FORM_ALAKAZAM_NORMAL (0)
#define FORM_ALAKAZAM_MEGA (1)
#define FORM_ALAKAZAM_COUNT (2)

#define FORM_SLOWBRO_NORMAL (0)
#define FORM_SLOWBRO_MEGA (1)
#define FORM_SLOWBRO_COUNT (2)

#define FORM_GENGAR_NORMAL (0)
#define FORM_GENGAR_MEGA (1)
#define FORM_GENGAR_COUNT (2)

#define FORM_KANGASKHAN_NORMAL (0)
#define FORM_KANGASKHAN_MEGA (1)
#define FORM_KANGASKHAN_COUNT (2)

#define FORM_PINSIR_NORMAL (0)
#define FORM_PINSIR_MEGA (1)
#define FORM_PINSIR_COUNT (2)

#define FORM_GYARADOS_NORMAL (0)
#define FORM_GYARADOS_MEGA (1)
#define FORM_GYARADOS_COUNT (2)

#define FORM_AERODACTYL_NORMAL (0)
#define FORM_AERODACTYL_MEGA (1)
#define FORM_AERODACTYL_COUNT (2)

#define FORM_MEWTWO_NORMAL (0)
#define FORM_MEWTWO_MEGAX (1)
#define FORM_MEWTWO_MEGAY (2)
#define FORM_MEWTWO_COUNT (3)

#define FORM_AMPHAROS_NORMAL (0)
#define FORM_AMPHAROS_MEGA (1)
#define FORM_AMPHAROS_COUNT (2)

#define FORM_UNOWN_A (0)
#define FORM_UNOWN_B (1)
#define FORM_UNOWN_C (2)
#define FORM_UNOWN_D (3)
#define FORM_UNOWN_E (4)
#define FORM_UNOWN_F (5)
#define FORM_UNOWN_G (6)
#define FORM_UNOWN_H (7)
#define FORM_UNOWN_I (8)
#define FORM_UNOWN_J (9)
#define FORM_UNOWN_K (10)
#define FORM_UNOWN_L (11)
#define FORM_UNOWN_M (12)
#define FORM_UNOWN_N (13)
#define FORM_UNOWN_O (14)
#define FORM_UNOWN_P (15)
#define FORM_UNOWN_Q (16)
#define FORM_UNOWN_R (17)
#define FORM_UNOWN_S (18)
#define FORM_UNOWN_T (19)
#define FORM_UNOWN_U (20)
#define FORM_UNOWN_V (21)
#define FORM_UNOWN_W (22)
#define FORM_UNOWN_X (23)
#define FORM_UNOWN_Y (24)
#define FORM_UNOWN_Z (25)
#define FORM_UNOWN_EXCLAMATION (26)
#define FORM_UNOWN_QUESTION (27)
#define FORM_UNOWN_COUNT (28)

#define FORM_STEELIX_NORMAL (0)
#define FORM_STEELIX_MEGA (1)
#define FORM_STEELIX_COUNT (2)

#define FORM_SCIZOR_NORMAL (0)
#define FORM_SCIZOR_MEGA (1)
#define FORM_SCIZOR_COUNT (2)

#define FORM_HERACROSS_NORMAL (0)
#define FORM_HERACROSS_MEGA (1)
#define FORM_HERACROSS_COUNT (2)

#define FORM_HOUNDOOM_NORMAL (0)
#define FORM_HOUNDOOM_MEGA (1)
#define FORM_HOUNDOOM_COUNT (2)

#define FORM_TYRANITAR_NORMAL (0)
#define FORM_TYRANITAR_MEGA (1)
#define FORM_TYRANITAR_COUNT (2)

#define FORM_SCEPTILE_NORMAL (0)
#define FORM_SCEPTILE_MEGA (1)
#define FORM_SCEPTILE_COUNT (2)

#define FORM_BLAZIKEN_NORMAL (0)
#define FORM_BLAZIKEN_MEGA (1)
#define FORM_BLAZIKEN_COUNT (2)

#define FORM_SWAMPERT_NORMAL (0)
#define FORM_SWAMPERT_MEGA (1)
#define FORM_SWAMPERT_COUNT (2)

#define FORM_GARDEVOIR_NORMAL (0)
#define FORM_GARDEVOIR_MEGA (1)
#define FORM_GARDEVOIR_COUNT (2)

#define FORM_SABLEYE_NORMAL (0)
#define FORM_SABLEYE_MEGA (1)
#define FORM_SABLEYE_COUNT (2)

#define FORM_MAWILE_NORMAL (0)
#define FORM_MAWILE_MEGA (1)
#define FORM_MAWILE_COUNT (2)

#define FORM_AGGRON_NORMAL (0)
#define FORM_AGGRON_MEGA (1)
#define FORM_AGGRON_COUNT (2)

#define FORM_MEDICHAM_NORMAL (0)
#define FORM_MEDICHAM_MEGA (1)
#define FORM_MEDICHAM_COUNT (2)

#define FORM_MANECTRIC_NORMAL (0)
#define FORM_MANECTRIC_MEGA (1)
#define FORM_MANECTRIC_COUNT (2)

#define FORM_SHARPEDO_NORMAL (0)
#define FORM_SHARPEDO_MEGA (1)
#define FORM_SHARPEDO_COUNT (2)

#define FORM_CAMERUPT_NORMAL (0)
#define FORM_CAMERUPT_MEGA (1)
#define FORM_CAMERUPT_COUNT (2)

#define FORM_ALTARIA_NORMAL (0)
#define FORM_ALTARIA_MEGA (1)
#define FORM_ALTARIA_COUNT (2)

#define FORM_CASTFORM_NORMAL (0)
#define FORM_CASTFORM_SUN (1)
#define FORM_CASTFORM_RAIN (2)
#define FORM_CASTFORM_SNOW (3)
#define FORM_CASTFORM_COUNT (4)

#define FORM_BANETTE_NORMAL (0)
#define FORM_BANETTE_MEGA (1)
#define FORM_BANETTE_COUNT (2)

#define FORM_ABSOL_NORMAL (0)
#define FORM_ABSOL_MEGA (1)
#define FORM_ABSOL_COUNT (2)

#define FORM_GLALIE_NORMAL (0)
#define FORM_GLALIE_MEGA (1)
#define FORM_GLALIE_COUNT (2)

#define FORM_SALAMENCE_NORMAL (0)
#define FORM_SALAMENCE_MEGA (1)
#define FORM_SALAMENCE_COUNT (2)

#define FORM_METAGROSS_NORMAL (0)
#define FORM_METAGROSS_MEGA (1)
#define FORM_METAGROSS_COUNT (2)

#define FORM_LATIAS_NORMAL (0)
#define FORM_LATIAS_MEGA (1)
#define FORM_LATIAS_COUNT (2)

#define FORM_LATIOS_NORMAL (0)
#define FORM_LATIOS_MEGA (1)
#define FORM_LATIOS_COUNT (2)

#define FORM_KYOGRE_NORMAL (0)
#define FORM_KYOGRE_ALPHA (1)
#define FORM_KYOGRE_COUNT (2)

#define FORM_GROUDON_NORMAL (0)
#define FORM_GROUDON_OMEGA (1)
#define FORM_GROUDON_COUNT (2)

#define FORM_RAYQUAZA_NORMAL (0)
#define FORM_RAYQUAZA_DELTA (1)
#define FORM_RAYQUAZA_COUNT (2)

#define FORM_DEOXYS_NORMAL (0)
#define FORM_DEOXYS_ATTACK (1)
#define FORM_DEOXYS_DEFENCE (2)
#define FORM_DEOXYS_SPEED (3)
#define FORM_DEOXYS_COUNT (4)

#define FORM_BURMY_PLANT (0)
#define FORM_BURMY_SAND (1)
#define FORM_BURMY_TRASH (2)
#define FORM_BURMY_COUNT (3)

#define FORM_WORMADAM_PLANT (0)
#define FORM_WORMADAM_GROUND (1)
#define FORM_WORMADAM_STEEL (2)
#define FORM_WORMADAM_COUNT (3)

#define FORM_CHERRIM_OVERCAST (0)
#define FORM_CHERRIM_SUNSHINE (1)
#define FORM_CHERRIM_COUNT (2)

#define FORM_SHELLOS_WEST (0)
#define FORM_SHELLOS_EAST (1)
#define FORM_SHELLOS_COUNT (2)

#define FORM_GASTRODON_WEST (0)
#define FORM_GASTRODON_EAST (1)
#define FORM_GASTRODON_COUNT (2)

#define FORM_LOPUNNY_NORMAL (0)
#define FORM_LOPUNNY_MEGA (1)
#define FORM_LOPUNNY_COUNT (2)

#define FORM_GARCHOMP_NORMAL (0)
#define FORM_GARCHOMP_MEGA (1)
#define FORM_GARCHOMP_COUNT (2)

#define FORM_LUCARIO_NORMAL (0)
#define FORM_LUCARIO_MEGA (1)
#define FORM_LUCARIO_COUNT (2)

#define FORM_ABOMASNOW_NORMAL (0)
#define FORM_ABOMASNOW_MEGA (1)
#define FORM_ABOMASNOW_COUNT (2)

#define FORM_GALLADE_NORMAL (0)
#define FORM_GALLADE_MEGA (1)
#define FORM_GALLADE_COUNT (2)

#define FORM_ROTOM_NORMAL (0)
#define FORM_ROTOM_HEAT (1)
#define FORM_ROTOM_WASH (2)
#define FORM_ROTOM_FROST (3)
#define FORM_ROTOM_FAN (4)
#define FORM_ROTOM_MOW (5)
#define FORM_ROTOM_COUNT (6)

#define FORM_GIRATINA_ALTERED (0)
#define FORM_GIRATINA_ORIGIN (1)
#define FORM_GIRATINA_COUNT (2)

#define FORM_SHAYMIN_LAND (0)
#define FORM_SHAYMIN_SKY (1)
#define FORM_SHAYMIN_COUNT (2)

#define FORM_ARCEUS_NORMAL (0)
#define FORM_ARCEUS_FIGHTING (1)
#define FORM_ARCEUS_FLYING (2)
#define FORM_ARCEUS_POISON (3)
#define FORM_ARCEUS_GROUND (4)
#define FORM_ARCEUS_ROCK (5)
#define FORM_ARCEUS_BUG (6)
#define FORM_ARCEUS_GHOST (7)
#define FORM_ARCEUS_STEEL (8)
#define FORM_ARCEUS_FIRE (9)
#define FORM_ARCEUS_WATER (10)
#define FORM_ARCEUS_GRASS (11)
#define FORM_ARCEUS_ELECTRIC (12)
#define FORM_ARCEUS_PSYCHIC (13)
#define FORM_ARCEUS_ICE (14)
#define FORM_ARCEUS_DRAGON (15)
#define FORM_ARCEUS_DARK (16)
#define FORM_ARCEUS_FAIRY (17)
#define FORM_ARCEUS_COUNT (18)

#define FORM_AUDINO_NORMAL (0)
#define FORM_AUDINO_MEGA (1)
#define FORM_AUDINO_COUNT (2)

#define FORM_BASCULIN_BLACK (0)
#define FORM_BASCULIN_WHITE (1)
#define FORM_BASCULIN_COUNT (2)

#define FORM_DARMANITAN_STANDARD (0)
#define FORM_DARMANITAN_ZEN (1)
#define FORM_DARMANITAN_COUNT (2)

#define FORM_DEERLING_SPRING (0)
#define FORM_DEERLING_SUMMER (1)
#define FORM_DEERLING_AUTUMN (2)
#define FORM_DEERLING_WINTER (3)
#define FORM_DEERLING_COUNT (4)

#define FORM_SAWSBUCK_SPRING (0)
#define FORM_SAWSBUCK_SUMMER (1)
#define FORM_SAWSBUCK_AUTUMN (2)
#define FORM_SAWSBUCK_WINTER (3)
#define FORM_SAWSBUCK_COUNT (4)

#define FORM_TORNADUS_INCARNATE (0)
#define FORM_TORNADUS_THERIAN (1)
#define FORM_TORNADUS_COUNT (2)

#define FORM_THUNDURUS_INCARNATE (0)
#define FORM_THUNDURUS_THERIAN (1)
#define FORM_THUNDURUS_COUNT (2)

#define FORM_LANDORUS_INCARNATE (0)
#define FORM_LANDORUS_THERIAN (1)
#define FORM_LANDORUS_COUNT (2)

#define FORM_KYUREM_NORMAL (0)
#define FORM_KYUREM_WHITE (1)
#define FORM_KYUREM_BLACK (2)
#define FORM_KYUREM_COUNT (3)

#define FORM_KELDEO_ORDINARY (0)
#define FORM_KELDEO_RESOLUTE (1)
#define FORM_KELDEO_COUNT (2)

#define FORM_MELOETTA_ARIA (0)
#define FORM_MELOETTA_PIROUETTE (1)
#define FORM_MELOETTA_COUNT (2)

#define FORM_GENESECT_NORMAL (0)
#define FORM_GENESECT_AQUA (1)
#define FORM_GENESECT_SHOCK (2)
#define FORM_GENESECT_BLAZE (3)
#define FORM_GENESECT_FREEZE (4)
#define FORM_GENESECT_COUNT (5)

#define FORM_VIVILLON_AREA1 (0)
#define FORM_VIVILLON_AREA2 (1)
#define FORM_VIVILLON_AREA3 (2)
#define FORM_VIVILLON_AREA4 (3)
#define FORM_VIVILLON_AREA5 (4)
#define FORM_VIVILLON_AREA6 (5)
#define FORM_VIVILLON_AREA7 (6)
#define FORM_VIVILLON_AREA8 (7)
#define FORM_VIVILLON_AREA9 (8)
#define FORM_VIVILLON_AREA10 (9)
#define FORM_VIVILLON_AREA11 (10)
#define FORM_VIVILLON_AREA12 (11)
#define FORM_VIVILLON_AREA13 (12)
#define FORM_VIVILLON_AREA14 (13)
#define FORM_VIVILLON_AREA15 (14)
#define FORM_VIVILLON_AREA16 (15)
#define FORM_VIVILLON_AREA17 (16)
#define FORM_VIVILLON_AREA18 (17)
#define FORM_VIVILLON_AREA19 (18)
#define FORM_VIVILLON_AREA20 (19)
#define FORM_VIVILLON_COUNT (20)

#define FORM_FLABEBE_RED (0)
#define FORM_FLABEBE_YELLOW (1)
#define FORM_FLABEBE_ORANGE (2)
#define FORM_FLABEBE_BLUE (3)
#define FORM_FLABEBE_WHITE (4)
#define FORM_FLABEBE_COUNT (5)

#define FORM_FLOETTE_RED (0)
#define FORM_FLOETTE_YELLOW (1)
#define FORM_FLOETTE_ORANGE (2)
#define FORM_FLOETTE_BLUE (3)
#define FORM_FLOETTE_WHITE (4)
#define FORM_FLOETTE_ETERNAL (5)
#define FORM_FLOETTE_COUNT (6)

#define FORM_FLORGES_RED (0)
#define FORM_FLORGES_YELLOW (1)
#define FORM_FLORGES_ORANGE (2)
#define FORM_FLORGES_BLUE (3)
#define FORM_FLORGES_WHITE (4)
#define FORM_FLORGES_COUNT (5)

#define FORM_FURFROU_NORMAL (0)
#define FORM_FURFROU_HEART (1)
#define FORM_FURFROU_STAR (2)
#define FORM_FURFROU_DIAMOND (3)
#define FORM_FURFROU_DEBUTANTE (4)
#define FORM_FURFROU_MATRON (5)
#define FORM_FURFROU_DANDY (6)
#define FORM_FURFROU_LA_REINE (7)
#define FORM_FURFROU_KABUKI (8)
#define FORM_FURFROU_PHARAOH (9)
#define FORM_FURFROU_COUNT (10)

#define FORM_MEOWSTIC_MALE (0)
#define FORM_MEOWSTIC_FEMALE (1)
#define FORM_MEOWSTIC_COUNT (2)

#define FORM_AEGISLASH_SHIELD (0)
#define FORM_AEGISLASH_BLADE (1)
#define FORM_AEGISLASH_COUNT (2)

#define FORM_PUMPKABOO_NORMAL (0)
#define FORM_PUMPKABOO_SMALL (1)
#define FORM_PUMPKABOO_LARGE (2)
#define FORM_PUMPKABOO_SUPER (3)
#define FORM_PUMPKABOO_COUNT (4)

#define FORM_GOURGEIST_NORMAL (0)
#define FORM_GOURGEIST_SMALL (1)
#define FORM_GOURGEIST_LARGE (2)
#define FORM_GOURGEIST_SUPER (3)
#define FORM_GOURGEIST_COUNT (4)

#define FORM_XERNEAS_NORMAL (0)
#define FORM_XERNEAS_ACTIVE (1)
#define FORM_XERNEAS_COUNT (2)

#define FORM_DIANCIE_NORMAL (0)
#define FORM_DIANCIE_MEGA (1)
#define FORM_DIANCIE_COUNT (2)

#define FORM_HOOPA_CONFINED (0)
#define FORM_HOOPA_UNBOUND (1)
#define FORM_HOOPA_COUNT (2)