/*
* Copyright (C) 2026 David Darras
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

/* ---------------------------------------------------------
 CHARACTER MODELS (X/Y base engine)
 --------------------------------------------------------- */
#define MODEL_NONE 0x0 /* No model drawn */
#define MODEL_SERENA 0x1 /* Female protagonist (X/Y) */
#define MODEL_CALEM 0x2 /* Male protagonist (X/Y) */
#define MODEL_SHAUNA 0x3 /* Friend B */
#define MODEL_TIERNO 0x4 /* Friend C */
#define MODEL_TREVOR 0x5 /* Friend D */
#define MODEL_PROFESSOR_SYCAMORE 0x6
#define MODEL_MOM 0x7
#define MODEL_MYSTERIOUS_WOMAN 0x8 /* Masked woman */
#define MODEL_MYSTERIOUS_MAN 0x9 /* Masked man */
#define MODEL_DIANTHA 0xa /* Champion */
#define MODEL_WIKSTROM 0xb /* Elite Four - Steel */
#define MODEL_MALVA 0xc /* Elite Four - Fire */
#define MODEL_DRASNA 0xd /* Elite Four - Dragon */
#define MODEL_SIEBOLD 0xe /* Elite Four - Water */
#define MODEL_VIOLA 0xf /* Gym Leader - Bug */
#define MODEL_GRANT 0x10 /* Gym Leader - Rock */
#define MODEL_KORRINA 0x11 /* Gym Leader - Fighting */
#define MODEL_RAMOS 0x12 /* Gym Leader - Grass */
#define MODEL_CLEMONT 0x13 /* Gym Leader - Electric */
#define MODEL_VALERIE 0x14 /* Gym Leader - Fairy */
#define MODEL_OLYMPIA 0x15 /* Gym Leader - Psychic */
#define MODEL_WULFRIC 0x16 /* Gym Leader - Ice */
#define MODEL_LYSANDRE 0x17 /* Team Flare boss */
#define MODEL_TEAM_FLARE_ADMIN_MALE 0x18
#define MODEL_TEAM_FLARE_ADMIN_FEMALE 0x19
#define MODEL_TEAM_FLARE_GRUNT_MALE 0x1a
#define MODEL_TEAM_FLARE_GRUNT_FEMALE 0x1b
#define MODEL_TEAM_FLARE_SCIENTIST_X 0x1c
#define MODEL_TEAM_FLARE_SCIENTIST_M 0x1d
#define MODEL_TEAM_FLARE_SCIENTIST_C 0x1e
#define MODEL_TEAM_FLARE_SCIENTIST_B 0x1f
#define MODEL_TEAM_FLARE_SCIENTIST_A 0x20
#define MODEL_AZ 0x21
#define MODEL_BATTLE_CHATEAU_NOBLE_A 0x22
#define MODEL_BATTLE_CHATEAU_NOBLE_B 0x23
#define MODEL_BATTLE_CHATEAU_NOBLE_C 0x24
#define MODEL_BATTLE_CHATEAU_NOBLE_D 0x25
#define MODEL_LOOKER 0x26 /* "Handsome" alias */
#define MODEL_LASS 0x27
#define MODEL_TODDLER_GIRL 0x28
#define MODEL_YOUNGSTER 0x29
#define MODEL_TODDLER_BOY 0x2a
#define MODEL_YOUNG_GIRL 0x2b
#define MODEL_SCHOOLGIRL 0x2c
#define MODEL_YOUNG_BOY 0x2d
#define MODEL_YOUNG_LADY 0x2e /* rich girl */
#define MODEL_WOMAN 0x2f
#define MODEL_SCHOOLBOY 0x30
#define MODEL_YOUNG_MAN 0x31
#define MODEL_RICH_BOY 0x32
#define MODEL_TOURIST_MALE 0x33
#define MODEL_TOURIST_FEMALE 0x34
#define MODEL_BACKPACKER 0x35
#define MODEL_SOCIALITE 0x36 /* Madame */
#define MODEL_GENTLEMAN 0x37
#define MODEL_BEAUTY 0x38
#define MODEL_PUNK_GUY 0x39 /* skinhead */
#define MODEL_PUNK_GIRL 0x3a
#define MODEL_PC_CLERK 0x3b /* PC box counter staff */
#define MODEL_SHOP_CLERK 0x3c
#define MODEL_GYM_GUIDE_DANPEI 0x3d
#define MODEL_RECEPTIONIST 0x3e
#define MODEL_BOUTIQUE_CLERK 0x3f
#define MODEL_DELIVERY_MAN 0x40
#define MODEL_HAIRDRESSER 0x41
#define MODEL_PHOTOGRAPHER 0x42
#define MODEL_LITTLE_BOY_SHORTS 0x43
#define MODEL_POKEFAN_MALE 0x44
#define MODEL_POKEFAN_FEMALE 0x45
#define MODEL_TWINS 0x46
#define MODEL_FASHIONISTA 0x47 /* miniskirt */
#define MODEL_SHOP_OWNER 0x48
#define MODEL_WAITRESS 0x49
#define MODEL_BATTLE_GIRL 0x4a
#define MODEL_ROLLER_SKATER_FEMALE 0x4b
#define MODEL_ROLLER_SKATER_MALE 0x4c
#define MODEL_FISHERMAN 0x4d
#define MODEL_RISING_STAR_FEMALE 0x4e
#define MODEL_ACE_TRAINER_FEMALE 0x4f
#define MODEL_VETERAN_FEMALE 0x50
#define MODEL_SWIMMER_MALE 0x51
#define MODEL_SWIMMER_FEMALE 0x52
#define MODEL_ARTIST_MALE 0x53
#define MODEL_ARTIST_FEMALE 0x54
#define MODEL_TRAVELER_FEMALE 0x55
#define MODEL_POKEMON_BREEDER_MALE 0x56
#define MODEL_POKEMON_BREEDER_FEMALE 0x57
#define MODEL_PSYCHIC_MALE 0x58
#define MODEL_RISING_STAR_MALE 0x59
#define MODEL_ACE_TRAINER_MALE 0x5a
#define MODEL_VETERAN_MALE 0x5b
#define MODEL_POKEMON_RANGER_MALE 0x5c
#define MODEL_POKEMON_RANGER_FEMALE 0x5d
#define MODEL_CHEF 0x5e
#define MODEL_RESEARCHER_MALE 0x5f
#define MODEL_RESEARCHER_FEMALE 0x60
#define MODEL_WORKER_A 0x61
#define MODEL_WORKER_B 0x62
#define MODEL_HEX_MANIAC 0x63
#define MODEL_FAIRY_TALE_GIRL 0x64
#define MODEL_BUTLER 0x65
#define MODEL_MAID 0x66
#define MODEL_GARDENER 0x67
#define MODEL_FURISODE_WHITE 0x68
#define MODEL_FURISODE_BLACK 0x69
#define MODEL_FURISODE_FLOWER 0x6a
#define MODEL_FURISODE_OCEAN 0x6b
#define MODEL_SKY_TRAINER_MALE 0x6c
#define MODEL_SKY_TRAINER_FEMALE 0x6d
#define MODEL_SURFING_ELITE_MALE 0x6e
#define MODEL_SURFING_ELITE_FEMALE 0x6f
#define MODEL_HIKER 0x70
#define MODEL_BLACK_BELT 0x71
#define MODEL_WAITER 0x72 /* garcon */
#define MODEL_APPRENTICE_MALE 0x73
#define MODEL_APPRENTICE_FEMALE 0x74
#define MODEL_CYCLIST 0x75
#define MODEL_TV_CREW 0x76
#define MODEL_MONSIEUR_KIZUNA 0x77
#define MODEL_SERENA_MANNEQUIN 0x78
#define MODEL_SERENA_MULTIPLAYER 0x79
#define MODEL_WORK_REF_00 0x7a /* variable-reference slots */
#define MODEL_WORK_REF_01 0x7b
#define MODEL_WORK_REF_02 0x7c
#define MODEL_WORK_REF_03 0x7d
#define MODEL_WORK_REF_04 0x7e
#define MODEL_WORK_REF_05 0x7f
#define MODEL_WORK_REF_06 0x80
#define MODEL_WORK_REF_07 0x81
#define MODEL_WORK_REF_08 0x82
#define MODEL_WORK_REF_09 0x83
#define MODEL_WORK_REF_10 0x84
#define MODEL_WORK_REF_11 0x85
#define MODEL_WORK_REF_12 0x86
#define MODEL_WORK_REF_13 0x87
#define MODEL_WORK_REF_14 0x88
#define MODEL_WORK_REF_15 0x89
#define MODEL_STOPPER 0x8a
#define MODEL_MYSTERIOUS_MAN_UNMASKED 0x8b
#define MODEL_MYSTERIOUS_WOMAN_UNMASKED 0x8c
#define MODEL_TRAVELER_FEMALE_STANDING 0x8d
#define MODEL_TRAVELER_FEMALE_SITTING 0x8e
#define MODEL_TOURIST_MALE_STANDING 0x8f
#define MODEL_TOURIST_FEMALE_STANDING 0x90
#define MODEL_TOURIST_MALE_SITTING 0x91
#define MODEL_TOURIST_FEMALE_SITTING 0x92
#define MODEL_RIVAL_MALE 0x93
#define MODEL_RIVAL_FEMALE 0x94
#define MODEL_3D_DUNGEON_ENEMY 0x95
#define MODEL_CALEM_MANNEQUIN 0x96
#define MODEL_MEGA_EVOLUTION_GURU 0x97
#define MODEL_GAME_DIRECTOR_CAMEO 0x98
#define MODEL_TALL_MAN 0x99
#define MODEL_VIOLAS_SISTER 0x9a /* Alexa */
#define MODEL_CLEMONTS_SISTER 0x9b /* Bonnie */
#define MODEL_LYSANDRE_ALT 0x9c
#define MODEL_C02_NPC_GIRL 0x9d
#define MODEL_C02_NPC_GIRL_EX 0x9e
#define MODEL_RIVAL_MALE_OMEGA 0x9f
#define MODEL_RIVAL_FEMALE_OMEGA 0xa0
#define MODEL_PGL_DELIVERY_MAN 0xa1
#define MODEL_TWINS_2 0xa2
#define MODEL_SWIMMER_MALE_2 0xa3
#define MODEL_SWIMMER_FEMALE_2 0xa4
#define MODEL_FISHERMAN_2 0xa5
#define MODEL_MIDDLE_AGED_MAN_2 0xa6
#define MODEL_FLUTE_PLAYER 0xa7 /* Black Belt with flute */
#define MODEL_GENTLEMAN_WITH_BOOK 0xa8
#define MODEL_WOMAN_WITH_BOOK 0xa9
#define MODEL_RESERVE_CHAR_4 0xaa

/* ---------------------------------------------------------
 CHARACTER MODELS (Ruby/Sapphire -> ORAS remake)
 --------------------------------------------------------- */
#define MODEL_MAY 0xab
#define MODEL_BRENDAN 0xac
#define MODEL_MAY_CONTEST 0xad
#define MODEL_BRENDAN_CONTEST 0xae
#define MODEL_MAY_MAGMA_SUIT 0xaf
#define MODEL_MAY_AQUA_SUIT 0xb0
#define MODEL_BRENDAN_MAGMA_SUIT 0xb1
#define MODEL_BRENDAN_AQUA_SUIT 0xb2
#define MODEL_PROFESSOR_BIRCH 0xb3
#define MODEL_RIVAL_ORAS 0xb4 /* Brendan/May, opposite gender */
#define MODEL_RIVAL_ORAS_WITH_BAG 0xb5
#define MODEL_STEVEN_STONE 0xb6
#define MODEL_SIDNEY 0xb7 /* Elite Four - Dark */
#define MODEL_PHOEBE 0xb8 /* Elite Four - Ghost */
#define MODEL_GLACIA 0xb9 /* Elite Four - Ice */
#define MODEL_DRAKE 0xba /* Elite Four - Dragon */
#define MODEL_ROXANNE 0xbb
#define MODEL_BRAWLY 0xbc
#define MODEL_WATTSON 0xbd
#define MODEL_FLANNERY 0xbe
#define MODEL_NORMAN 0xbf
#define MODEL_WINONA 0xc0
#define MODEL_TATE 0xc1
#define MODEL_LIZA 0xc2
#define MODEL_JUAN 0xc3
#define MODEL_MAXIE 0xc4
#define MODEL_TABITHA 0xc5
#define MODEL_COURTNEY 0xc6
#define MODEL_TEAM_MAGMA_GRUNT_MALE 0xc7
#define MODEL_TEAM_MAGMA_GRUNT_FEMALE 0xc8
#define MODEL_ARCHIE 0xc9
#define MODEL_MATT 0xca
#define MODEL_SHELLY 0xcb
#define MODEL_TEAM_AQUA_GRUNT_MALE 0xcc
#define MODEL_TEAM_AQUA_GRUNT_FEMALE 0xcd
#define MODEL_BATTLE_RESORT_BOSS_GREEN 0xce
#define MODEL_BATTLE_RESORT_BOSS_RED 0xcf
#define MODEL_BATTLE_RESORT_BOSS_BLUE 0xd0
#define MODEL_BATTLE_RESORT_BOSS_YELLOW 0xd1
#define MODEL_CONTEST_NPC 0xd2
#define MODEL_SECRET_BASE_NPC 0xd3
#define MODEL_ZINNIA 0xd4
#define MODEL_ZINNIA_MAGMA 0xd5
#define MODEL_ZINNIA_AQUA 0xd6
#define MODEL_LOOKER_ORAS 0xd7
#define MODEL_MAIN_STORY_NPC_1 0xd8
#define MODEL_MAIN_STORY_NPC_2 0xd9
#define MODEL_YOUNGSTER_SHORTS 0xda
#define MODEL_LASS_MINISKIRT 0xdb
#define MODEL_BUG_CATCHER 0xdc
#define MODEL_SCHOOLKID_MALE 0xdd
#define MODEL_SCHOOLKID_FEMALE 0xde
#define MODEL_CAMPER 0xdf
#define MODEL_PICNICKER 0xe0
#define MODEL_RICH_BOY_ORAS 0xe1
#define MODEL_RICH_GIRL_ORAS 0xe2
#define MODEL_TUBE_KID_MALE 0xe3 /* inflatable ring */
#define MODEL_TUBE_KID_FEMALE 0xe4
#define MODEL_SWIMMER_MALE_ORAS 0xe5
#define MODEL_SWIMMER_FEMALE_ORAS 0xe6
#define MODEL_GENTLEMAN_ORAS 0xe7
#define MODEL_SAILOR 0xe8
#define MODEL_HIKER_ORAS 0xe9
#define MODEL_POKEMON_BREEDER_MALE_ORAS 0xea
#define MODEL_POKEMON_BREEDER_FEMALE_ORAS 0xeb
#define MODEL_BLACK_BELT_ORAS 0xec
#define MODEL_BATTLE_GIRL_ORAS 0xed
#define MODEL_POKEMON_COLLECTOR 0xee
#define MODEL_FISHERMAN_ORAS 0xef
#define MODEL_MONSTER_MANIAC 0xf0
#define MODEL_BUG_MANIAC 0xf1
#define MODEL_RUIN_MANIAC 0xf2
#define MODEL_HEX_MANIAC_ORAS 0xf3
#define MODEL_PSYCHIC_MALE_ORAS 0xf4
#define MODEL_NINJA_BOY 0xf5
#define MODEL_CAMPFIRE_NPC 0xf6
#define MODEL_BIRD_KEEPER 0xf7
#define MODEL_DRAGON_TAMER 0xf8
#define MODEL_GUITARIST 0xf9
#define MODEL_POKEMON_RANGER_MALE_ORAS 0xfa
#define MODEL_POKEMON_RANGER_FEMALE_ORAS 0xfb
#define MODEL_BEAUTY_ORAS 0xfc
#define MODEL_PARASOL_LADY 0xfd
#define MODEL_AROMA_LADY 0xfe
#define MODEL_POKEFAN_MALE_ORAS 0xff
#define MODEL_POKEFAN_FEMALE_ORAS 0x100
#define MODEL_TRIATHLETE_RUNNER 0x101
#define MODEL_TRIATHLETE_CYCLIST 0x102
#define MODEL_TRIATHLETE_SWIMMER 0x103
#define MODEL_ACE_TRAINER_MALE_ORAS 0x104
#define MODEL_ACE_TRAINER_FEMALE_ORAS 0x105
#define MODEL_VETERAN_MALE_ORAS 0x106
#define MODEL_VETERAN_FEMALE_ORAS 0x107
#define MODEL_REPORTER 0x108
#define MODEL_CAMERAMAN_ORAS 0x109
#define MODEL_TWINS_1_ORAS 0x10a
#define MODEL_TWINS_2_ORAS 0x10b
#define MODEL_LOVEY_DOVEY_COUPLE_MALE 0x10c
#define MODEL_LOVEY_DOVEY_COUPLE_FEMALE 0x10d
#define MODEL_SENIOR 0x10e /* sempai */
#define MODEL_JUNIOR 0x10f /* kohai */
#define MODEL_FAIRY_TALE_GIRL_ORAS 0x110
#define MODEL_SURFING_ELITE_MALE_ORAS 0x111
#define MODEL_SURFING_ELITE_FEMALE_ORAS 0x112
#define MODEL_BACKPACKER_ORAS 0x113
#define MODEL_SCARY_MAN 0x114
#define MODEL_SCARY_WOMAN 0x115
#define MODEL_DIVER_MALE 0x116
#define MODEL_DIVER_FEMALE 0x117
#define MODEL_MOM_ORAS 0x118
#define MODEL_WALLY 0x119
#define MODEL_MR_STONE 0x11a /* Steven's father */
#define MODEL_OLD_MAN_HAGI 0x11b
#define MODEL_TODDLER_BOY_ORAS 0x11c
#define MODEL_TODDLER_GIRL_ORAS 0x11d
#define MODEL_OLD_MAN_KIMONO 0x11e
#define MODEL_OLD_WOMAN_KIMONO 0x11f
#define MODEL_MIDDLE_AGED_MAN_BALD 0x120
#define MODEL_MIDDLE_AGED_MAN_STOUT 0x121
#define MODEL_TRENDY_OLD_MAN 0x122
#define MODEL_FAIRY_TALE_OLD_MAN 0x123
#define MODEL_SINGER_SONGWRITER_OLD_MAN 0x124
#define MODEL_ITEM_TRADER_OLD_MAN 0x125
#define MODEL_LEGENDARY_OLD_MAN 0x126
#define MODEL_MECHANICAL_KING 0x127 /* karakuri daiou */
#define MODEL_MIDDLE_AGED_WOMAN 0x128
#define MODEL_SUNGLASSES_GUY 0x129
#define MODEL_PC_LADY 0x12a
#define MODEL_SHOP_CLERK_ORAS 0x12b
#define MODEL_RECEPTIONIST_ORAS 0x12c
#define MODEL_GYM_GUIDE_DANPEI_ORAS 0x12d
#define MODEL_DELIVERY_MAN_1 0x12e
#define MODEL_DELIVERY_MAN_2 0x12f
#define MODEL_CONTEST_MC 0x130
#define MODEL_YOUNG_GIRL_ORAS 0x131
#define MODEL_YOUNG_MAN_ORAS 0x132
#define MODEL_RESEARCHER_MALE_ORAS 0x133
#define MODEL_MONSIEUR_KIZUNA_ORAS 0x134
#define MODEL_CAPTAIN_KUSUNOKI 0x135
#define MODEL_PROFESSOR_SORAISHI 0x136
#define MODEL_FURISODE_FLOWER_ORAS 0x137
#define MODEL_STOPPER_3 0x138
#define MODEL_GAME_DIRECTOR_CAMEO_ORAS 0x139
#define MODEL_SUPPORT_MAY 0x13a /* multiplayer helper */
#define MODEL_SUPPORT_BRENDAN 0x13b
#define MODEL_SUPPORT_MAY_BIKE 0x13c
#define MODEL_SUPPORT_BRENDAN_BIKE 0x13d
#define MODEL_PROFESSOR_BIRCH_PANICKED 0x13e
#define MODEL_NORMAN_SHOES 0x13f
#define MODEL_OFFICE_WORKER 0x140
#define MODEL_BOY_WITH_3DS 0x141
#define MODEL_GENERIC_WOMAN 0x142
#define MODEL_YOUNGSTER_SHORTS_BAREFOOT 0x143
#define MODEL_LASS_MINISKIRT_BAREFOOT 0x144
#define MODEL_SCHOOLKID_MALE_BAREFOOT 0x145
#define MODEL_SCHOOLKID_FEMALE_BAREFOOT 0x146
#define MODEL_HIKER_BAREFOOT 0x147
#define MODEL_AROMA_LADY_BAREFOOT 0x148
#define MODEL_ACE_TRAINER_MALE_BAREFOOT 0x149
#define MODEL_ACE_TRAINER_FEMALE_BAREFOOT 0x14a
#define MODEL_VETERAN_MALE_BAREFOOT 0x14b
#define MODEL_VETERAN_FEMALE_BAREFOOT 0x14c
#define MODEL_SCARY_MAN_BAREFOOT 0x14d
#define MODEL_SCARY_WOMAN_BAREFOOT 0x14e
#define MODEL_OLD_MAN_HAGI_BAREFOOT 0x14f
#define MODEL_TODDLER_BOY_BAREFOOT 0x150
#define MODEL_TODDLER_GIRL_BAREFOOT 0x151
#define MODEL_OLD_MAN_KIMONO_BAREFOOT 0x152
#define MODEL_OLD_WOMAN_KIMONO_BAREFOOT 0x153
#define MODEL_MIDDLE_AGED_MAN_BALD_BAREFOOT 0x154
#define MODEL_MIDDLE_AGED_MAN_STOUT_BAREFOOT 0x155
#define MODEL_MIDDLE_AGED_WOMAN_BAREFOOT 0x156
#define MODEL_YOUNG_MAN_BAREFOOT 0x157
#define MODEL_FISHERMAN_2_ORAS 0x158
#define MODEL_SWIMMER_FEMALE_2_ORAS 0x159
#define MODEL_SWIMMER_MALE_2_ORAS 0x15a
#define MODEL_TUBE_KID_MALE_2 0x15b
#define MODEL_TUBE_KID_FEMALE_2 0x15c
#define MODEL_BRAWLY_ALT_POSE 0x15d
#define MODEL_PHOEBE_ALT_POSE 0x15e
#define MODEL_WINONA_ALT_POSE 0x15f
#define MODEL_SIDNEY_ALT_POSE 0x160
#define MODEL_MAYUMI 0x161

/* ---------------------------------------------------------
 OBJECTS / ITEMS / SCENERY
 --------------------------------------------------------- */
#define MODEL_POKEBALL 0x162
#define MODEL_POKEBALL_RARE 0x163
#define MODEL_GRASS_RUSTLE_EFFECT 0x164
#define MODEL_WATER_SPLASH_EFFECT 0x165
#define MODEL_DUST_CLOUD_EFFECT 0x166
#define MODEL_FLYING_POKEMON_EFFECT 0x167
#define MODEL_CEILING_POKEMON_EFFECT 0x168
#define MODEL_LEAF_EFFECT 0x169
#define MODEL_SNOW_EFFECT 0x16a
#define MODEL_STRENGTH_BOULDER 0x16b
#define MODEL_STRENGTH_BOULDER_LARGE 0x16c
#define MODEL_CUT_TREE 0x16d
#define MODEL_ROCK_SMASH_BOULDER 0x16e
#define MODEL_RHYHORN_BREAKABLE_ROCK 0x16f
#define MODEL_BERRY_TREE 0x170
#define MODEL_FOSSIL_1 0x171
#define MODEL_FOSSIL_2 0x172
#define MODEL_BERRY_TREE_02 0x173
#define MODEL_BERRY_TREE_03 0x174
#define MODEL_BERRY_TREE_04 0x175
#define MODEL_BERRY_TREE_05 0x176
#define MODEL_BERRY_TREE_06 0x177
#define MODEL_BERRY_TREE_07 0x178
#define MODEL_BERRY_TREE_08 0x179
#define MODEL_BERRY_TREE_09 0x17a
#define MODEL_BERRY_TREE_10 0x17b
#define MODEL_BERRY_TREE_11 0x17c
#define MODEL_BERRY_TREE_12 0x17d
#define MODEL_BERRY_TREE_13 0x17e
#define MODEL_BERRY_TREE_14 0x17f
#define MODEL_BERRY_TREE_15 0x180
#define MODEL_BERRY_TREE_16 0x181
#define MODEL_BERRY_TREE_17 0x182
#define MODEL_BERRY_TREE_18 0x183
#define MODEL_BERRY_TREE_19 0x184
#define MODEL_BERRY_TREE_20 0x185
#define MODEL_BERRY_TREE_21 0x186
#define MODEL_BERRY_TREE_22 0x187
#define MODEL_BERRY_TREE_23 0x188
#define MODEL_BERRY_TREE_24 0x189
#define MODEL_BERRY_TREE_25 0x18a
#define MODEL_BERRY_TREE_26 0x18b
#define MODEL_BERRY_TREE_27 0x18c
#define MODEL_BERRY_TREE_28 0x18d
#define MODEL_BERRY_TREE_29 0x18e
#define MODEL_BERRY_TREE_30 0x18f
#define MODEL_BERRY_TREE_31 0x190
#define MODEL_BERRY_TREE_32 0x191
#define MODEL_BERRY_TREE_33 0x192
#define MODEL_BERRY_TREE_34 0x193
#define MODEL_BERRY_TREE_35 0x194
#define MODEL_BERRY_TREE_36 0x195
#define MODEL_ROCK_SMASH_WALL 0x196
#define MODEL_MAMOSWINE_BREAKABLE_SNOW 0x197
#define MODEL_KALOS_DEX_AWARD 0x198
#define MODEL_NATIONAL_DEX_AWARD 0x199
#define MODEL_XERNEAS_TREE 0x19a
#define MODEL_YVELTAL_COCOON 0x19b
#define MODEL_PLAINS_DEX_AWARD 0x19c
#define MODEL_COASTAL_DEX_AWARD 0x19d
#define MODEL_MOUNTAIN_DEX_AWARD 0x19e
#define MODEL_SPARKLE_EFFECT 0x19f
#define MODEL_TRAFFIC_CONE 0x1a0
#define MODEL_SUNGLASSES_PROP 0x1a1
#define MODEL_FOOD_CLOCHE 0x1a2
#define MODEL_HOTEL_TABLE 0x1a3
#define MODEL_SPARKLE_EFFECT_2 0x1a4
#define MODEL_POKEMON_FLUTE 0x1a5
#define MODEL_COFFEE_CUP 0x1a6
#define MODEL_BOOK 0x1a7
#define MODEL_RESERVE_OBJECT_4 0x1a8
#define MODEL_HOENN_DEX_AWARD 0x1a9
#define MODEL_NATIONAL_DEX_AWARD_ORAS 0x1aa
#define MODEL_PROFESSOR_BIRCH_BAG 0x1ab
#define MODEL_AZURILL_DOLL 0x1ac
#define MODEL_SKITTY_DOLL 0x1ad
#define MODEL_SWABLU_DOLL 0x1ae
#define MODEL_LAPRAS_DOLL 0x1af
#define MODEL_SNORLAX_DOLL 0x1b0
#define MODEL_BLUE_ORB 0x1b1
#define MODEL_RED_ORB 0x1b2
#define MODEL_FOSSIL_ORAS 0x1b3
#define MODEL_KEYSTONE_TABLET 0x1b4
#define MODEL_MONOLITH 0x1b5
#define MODEL_GENERIC_FLYING_BIRD 0x1b6
#define MODEL_HOOPAS_RING 0x1b7
#define MODEL_MAGMA_SUIT_PROP 0x1b8
#define MODEL_AQUA_SUIT_PROP 0x1b9
#define MODEL_TIDE_POOL_WATER 0x1ba
#define MODEL_TIDE_POOL_SHELL 0x1bb
#define MODEL_NATURE_STOPPER 0x1bc
#define MODEL_STEVENS_LETTER 0x1bd

/* ---------------------------------------------------------
 COMPANION / RIDE POKEMON
 --------------------------------------------------------- */
#define MODEL_PUMPKABOO_STAGE1 0x1be
#define MODEL_DIGGERSBY_STAGE2 0x1bf
#define MODEL_PACKAGE_POKEMON_ZYGARDE 0x1c0
#define MODEL_LITLEO_STAGE1 0x1c1
#define MODEL_GOGOAT_STAGE2 0x1c2
#define MODEL_UNUSED_1 0x1c3
#define MODEL_SLEEPING_RHYHORN 0x1c4
#define MODEL_MAMOSWINE 0x1c5
#define MODEL_RIDEABLE_GOGOAT 0x1c6
#define MODEL_LUCARIO 0x1c7
#define MODEL_FURFROU_NATURAL 0x1c8
#define MODEL_FLETCHLING 0x1c9
#define MODEL_SNORLAX 0x1ca
#define MODEL_ESPURR 0x1cb
#define MODEL_LAPRAS 0x1cc
#define MODEL_RHYHORN_SPECIAL 0x1cd
#define MODEL_ABOMASNOW 0x1ce
#define MODEL_UNRIDEABLE_GOAT 0x1cf
#define MODEL_UNUSED_2 0x1d0
#define MODEL_AZUMARILL 0x1d1
#define MODEL_RHYHORN_TUTORIAL 0x1d2
#define MODEL_PACKAGE_POKEMON_XERNEAS 0x1d3
#define MODEL_PACKAGE_POKEMON_YVELTAL 0x1d4
#define MODEL_MEWTWO 0x1d5
#define MODEL_RESERVE_POKEMON_2 0x1d6
#define MODEL_RESERVE_POKEMON_3 0x1d7
#define MODEL_RESERVE_POKEMON_4 0x1d8
#define MODEL_GROUDON 0x1d9
#define MODEL_MEGA_GROUDON 0x1da
#define MODEL_KYOGRE 0x1db
#define MODEL_MEGA_KYOGRE 0x1dc
#define MODEL_RAYQUAZA 0x1dd
#define MODEL_MEGA_RAYQUAZA 0x1de
#define MODEL_LATIAS 0x1df
#define MODEL_LATIOS 0x1e0
#define MODEL_MEGA_LATIAS 0x1e1
#define MODEL_MEGA_LATIOS 0x1e2
#define MODEL_MACHOKE 0x1e3
#define MODEL_WINGULL 0x1e4
#define MODEL_CORPHISH 0x1e5
#define MODEL_TROPIUS 0x1e6
#define MODEL_KECLEON 0x1e7
#define MODEL_REGIROCK 0x1e8
#define MODEL_REGICE 0x1e9
#define MODEL_REGISTEEL 0x1ea
#define MODEL_POOCHYENA 0x1eb
#define MODEL_SKITTY 0x1ec
#define MODEL_ZIGZAGOON 0x1ed
#define MODEL_WAILMER 0x1ee
#define MODEL_PLUSLE 0x1ef
#define MODEL_MINUN 0x1f0
#define MODEL_MEDITITE 0x1f1
#define MODEL_SHROOMISH 0x1f2
#define MODEL_SLAKOTH 0x1f3
#define MODEL_ROSELIA 0x1f4
#define MODEL_TAILLOW 0x1f5
#define MODEL_HOOPA 0x1f6
#define MODEL_WHISMUR 0x1f7
#define MODEL_ELECTRIKE 0x1f8
#define MODEL_ALTARIA 0x1f9
#define MODEL_BARKING_POOCHYENA 0x1fa
#define MODEL_PETRIFIED_GROUDON 0x1fb
#define MODEL_PETRIFIED_KYOGRE 0x1fc
#define MODEL_MACHOKE_ALT 0x1fd

/* ---------------------------------------------------------
 SUB-OBJECTS (held items / mounts shown on characters)
 --------------------------------------------------------- */
#define MODEL_SUB_BASE 0x1fe
#define MODEL_SUB_BICYCLE 0x1fe
#define MODEL_SUB_WAILMER_WHALE 0x1ff
#define MODEL_SUB_FISHING_ROD 0x200
#define MODEL_SUB_BICYCLE_2 0x201
#define MODEL_SUB_POKEBALL 0x202
#define MODEL_SUB_PENCIL 0x203
#define MODEL_SUB_POKEBALL_RARE 0x204
#define MODEL_SUB_BIRD 0x205
#define MODEL_SUB_FISHING_ROD_2 0x206
#define MODEL_SUB_FISHING_ROD_3 0x207
#define MODEL_SUB_DOWSING_MACHINE 0x208
#define MODEL_SUB_WATERING_CAN 0x209
#define MODEL_SUB_LAPRAS 0x20a
#define MODEL_SUB_RESERVE_1 0x20b
#define MODEL_SUB_RESERVE_2 0x20c
#define MODEL_SUB_RESERVE_3 0x20d
#define MODEL_SUB_RESERVE_4 0x20e
#define MODEL_SUB_SURF_KYOGRE 0x20f
#define MODEL_SUB_DIVE_KYOGRE 0x210
#define MODEL_SUB_GROUDON 0x211
#define MODEL_SUB_DIVE_LAPRAS 0x212
#define MODEL_SUB_SURF_SHARPEDO 0x213
#define MODEL_SUB_DIVE_SHARPEDO 0x214
#define MODEL_SUB_SURF_WAILORD 0x215
#define MODEL_SUB_DIVE_WAILORD 0x216
#define MODEL_SUB_DEVON_SCOPE 0x217
#define MODEL_SUB_ACRO_BIKE 0x218
#define MODEL_SUB_MACH_BIKE 0x219
#define MODEL_SUB_DOWSING_MACHINE_ORAS 0x21a
#define MODEL_SUB_WATERING_CAN_ORAS 0x21b
#define MODEL_SUB_FOSSIL 0x21c
#define MODEL_SUB_PENCIL_M 0x21d
#define MODEL_SUB_DOWSING_MACHINE_M 0x21e
#define MODEL_SUB_DEVON_SCOPE_M 0x21f
