/*
 * Copyright (C) 2026  David Darras
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <types.h>

enum class Platform : u8 {
  kNone = 0,
  kGrass = 1,
  kFactory = 2,
  kCave = 3,
  kForest = 4,
  kShore = 5,
  kMountain = 6,
  kRoom = 7,
  kCity = 8,
  kTown = 9,
  kPalace = 10,
  kCommRoom = 11,
  kPondWater = 12,
  kOceanSurface = 13,
  kFrostCave = 14,
  kReflectionCave = 15,
  kGymRockTrainer = 16,
  kGymFightingTrainer = 17,
  kGymElectricTrainer = 18,
  kGymFireTrainer = 19,
  kGymNormalTrainer = 20,
  kGymFlyingTrainer = 21,
  kGymPsychicTrainer = 22,
  kGymWaterTrainer = 23,
  kEliteFourSidney = 24,
  kEliteFourPhoebe = 25,
  kEliteFourGlacia = 26,
  kEliteFourDrake = 27,
  kChampionSteven = 28,
  kDarkRoom = 29,
  kWcsPokemonLeague = 30,
  kWcsPokemonLeagueAlt = 31,
  kGymRoxanne = 32,
  kGymBrawly = 33,
  kGymWattson = 34,
  kGymFlannery = 35,
  kGymNorman = 36,
  kGymWinona = 37,
  kGymTateLiza = 38,
  kGymWallace = 39,
  kSkyBattle = 40,
  kWaterCave = 41,
  kGrey = 42,
  kDesert = 43,
  kVolcanicAsh = 44,
  kBeachSide = 45,
  kShallowWater = 46,
  kShallowWaterCity = 47,
  kUnderwaterSeabed = 48,
  kGraniteCave = 49,
  kMeteorFalls = 50,
  kSeafloorCave = 51,
  kWaterfall = 52,
  kTeamAquaHideout = 53,
  kCyclingRoad = 54,
  kSSCactus = 55,
  kMtPyreCemetery = 56,
  kSkyPillar = 57,
  kGroudonPrimal = 58,
  kKyogrePrimal = 59,
  kRayquazaMega = 60,
  kLegendaryRing = 61,
  kContestNormalCool = 62,
  kContestNormalBeautiful = 63,
  kContestNormalCute = 64,
  kContestNormalClever = 65,
  kContestNormalTough = 66,
  kContestSuperCool = 67,
  kContestSuperBeautiful = 68,
  kContestSuperCute = 69,
  kContestSuperClever = 70,
  kContestSuperTough = 71,
  kContestHyperCool = 72,
  kContestHyperBeautiful = 73,
  kContestHyperCute = 74,
  kContestHyperClever = 75,
  kContestHyperTough = 76,
  kContestMasterCool = 77,
  kContestMasterBeautiful = 78,
  kContestMasterCute = 79,
  kContestMasterClever = 80,
  kContestMasterTough = 81,
  kContestIntro = 82,
  kContestResults = 83,
  kArchieBoss = 84,
  kMaxieBoss = 85,
  kSkyPillarTop = 86,
  kDeoxysDna = 87,
  kFieryPath = 88,
  kWallyVictoryRoad = 89,
  kPlain = 90,
  kGreyAlt = 91,
};
