/*
 * Copyright (C) 2026  David Darras
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

static const char* OPOWERS[] = {
    "None",
    "Hatching Power Lv. 1",
    "Hatching Power Lv. 2",
    "Hatching Power Lv. 3",
    "Hatching Power S",
    "Hatching Power MAX",
    "Bargain Power Lv. 1",
    "Bargain Power Lv. 2",
    "Bargain Power Lv. 3",
    "Bargain Power S",
    "Bargain Power MAX",
    "Prize Money Power Lv. 1",
    "Prize Money Power Lv. 2",
    "Prize Money Power Lv. 3",
    "Prize Money Power S",
    "Prize Money Power MAX",
    "Exp. Point Power Lv. 1",
    "Exp. Point Power Lv. 2",
    "Exp. Point Power Lv. 3",
    "Exp. Point Power S",
    "Exp. Point Power MAX",
    "Capture Power Lv. 1",
    "Capture Power Lv. 2",
    "Capture Power Lv. 3",
    "Capture Power S",
    "Capture Power MAX",
    "Encounter Power Lv. 1",
    "Encounter Power Lv. 2",
    "Encounter Power Lv. 3",
    "Stealth Power Lv. 1",
    "Stealth Power Lv. 2",
    "Stealth Power Lv. 3",
    "HP Restoring Power Lv. 1",
    "HP Restoring Power Lv. 2",
    "HP Restoring Power Lv. 3",
    "PP Restoring Power Lv. 1",
    "PP Restoring Power Lv. 2",
    "PP Restoring Power Lv. 3",
    "HP Restoring Power MAX",
    "Friendship Power Lv. 1",
    "Friendship Power Lv. 2",
    "Friendship Power Lv. 3",
    "Friendship Power S",
    "Friendship Power MAX",
    "Attack Power Lv. 1",
    "Attack Power Lv. 2",
    "Attack Power Lv. 3",
    "Defense Power Lv. 1",
    "Defense Power Lv. 2",
    "Defense Power Lv. 3",
    "Sp. Atk. Power Lv. 1",
    "Sp. Atk. Power Lv. 2",
    "Sp. Atk. Power Lv. 3",
    "Sp. Def. Power Lv. 1",
    "Sp. Def. Power Lv. 2",
    "Sp. Def. Power Lv. 3",
    "Speed Power Lv. 1",
    "Speed Power Lv. 2",
    "Speed Power Lv. 3",
    "Critical Power Lv. 1",
    "Critical Power Lv. 2",
    "Critical Power Lv. 3",
    "Accuracy Power Lv. 1",
    "Accuracy Power Lv. 2",
    "Accuracy Power Lv. 3"
};

static const char* FIELD_OPOWERS[] = {
    "Encounter Power",
    "Hatching Power",
    "Bargain Power",
    "Prize Money Power",
    "Exp. Point Power",
    "Capture Power",
    "Stealth Power",
    "HP Restoring Power",
    "PP Restoring Power",
    "Friendship Power"
};

static const char* BATTLE_OPOWERS[] = {
    "Attack Power",
    "Defense Power",
    "Sp. Atk. Power",
    "Sp. Def. Power",
    "Speed Power",
    "Critical Power",
    "Accuracy Power"
};