/*
 * Copyright (C) 2026  David Darras
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <types.h>

enum class ArchiveID : u32 {
  kStatus = 0, // Pokemon summary layouts
  kStatusModel = 1, // Status screen cameras
  kPokeList = 2, // Party selection layouts
  kBattle3d = 3, // Battle camera animations
  kBattleLayout = 4,
  kBattleApp = 5, // In-battle lower screen UI
  kMoveMotionTable = 6,
  kBattleAi = 7, // Trainer AI pawn scripts
  kPokemonModel = 8,
  kFade = 9, // Zone change transition fade
  kSkybox = 10, // Skybox and weather
  kMenuAppWindow = 11,
  kMenuAmieWindow = 12,
  kZoneData = 13,
  kOverworldArea = 14,
  kConfig = 15, // Options menu layout
  kAmieGameBerryPicker = 16,
  kAmieGameHeadIt = 17,
  kAmieGameTilePuzzle = 18,
  kNameInput = 19, // Name input layouts
  kNameInputData = 20, // Keyboard button labels
  kOverworldModel = 21,
  kOverworldModelParam = 22, // NPC model descriptors/configs
  kPropModel = 23,
  kFieldMenu = 24, // Field bottom screen title panels
  kFieldMenuPss = 25,
  kAmieFieldUi = 26,
  kFieldMenuTraining = 27, // Super Training field UI
  kTrainingCommon = 28, // Super Training regimen selection
  kFieldScript = 29, // Global AMX scripts
  kMoveLearn = 30,
  kMoveEffectParticle = 31,
  kMoveEffectModel = 32,
  kMoveEffectLayout = 33, // Battle intro layouts
  kMoveSequence = 34, // Move cutscene sequences
  kAmieEffect = 35, // Amie scene Pokemon emotions
  kTrainerData = 36,
  kTrainerTypeData = 37, // Trainer classes
  kTrainerPokemonData = 38,
  kMapLandData = 39, // Field chunk graphics residents
  kMapMatrix = 40,
  kAmieMenu = 41,
  kAmieIcon = 42,
  kPssBattleReceive = 43, // PSS connection layouts
  kPssProfile = 44,
  kPssInviteWindow = 45,
  kPssInterfereWindow = 46, // PSS field overlay layout
  kPssUserNotify = 47,
  kPssMessageWindow = 48,
  kPssIconSelect = 49,
  kPssPlaySelect = 50, // Battle/trade connection method select
  kPssFavorite = 51,
  kPssPlayerSelect = 52,
  kPssYesNoDialog = 53,
  kPssMainMenu = 54,
  kPssConfig = 55,
  kPssCharacterMenu = 56, // Player view/interaction layout
  kPssMatching = 57, // Battle setup layout
  kPssInterfereInfo = 58,
  kFieldAreaEnvironment = 59, // Skybox/textures for field battle
  kWeather = 60, // Field weather effects
  kBag = 61,
  kFieldCameraAnimation = 62,
  kBattleShaders = 63, // kujira_CullingShader
  kFieldEffect = 64, // Field effect package
  kBattleSpot = 65, // PSS battle spot UI
  kTownMapInfo = 66, // Town map target data
  kTownMapLayout = 67,
  kTownMapNaviLayout = 68,
  kTitleMenuLayout = 69, // Title/Mystery Gift/Live Com UI
  kSaveDataLayout = 70,
  kGameTextJapanese = 71,
  kGameTextKanji = 72,
  kGameTextEnglish = 73,
  kGameTextFrench = 74,
  kGameTextItalian = 75,
  kGameTextGerman = 76,
  kGameTextSpanish = 77,
  kGameTextKorean = 78,
  kScriptMessageJapanese = 79, // Story + NPC text
  kScriptMessageJapaneseKanji = 80,
  kScriptMessageEnglish = 81,
  kScriptMessageFrench = 82,
  kScriptMessageItalian = 83,
  kScriptMessageGerman = 84,
  kScriptMessageSpanish = 85,
  kScriptMessageKorean = 86,
  kFieldDressUpData = 87, // Trainer customization field models, unused in ORAS
  kBattleDressUpData = 88, // Trainer customization battle models
  kAmieScript = 89,
  kBoutique = 90, // Kisekae shop UI
  kPokemonIcon = 91,
  kItemIcon = 92,
  kMoveCategoryIcon = 93, // Physical/Special/Status damage icons
  kMessageWindow = 94, // Generic message UI layouts
  kPokeListCommon = 95, // EXP bar, HP bar, held item icon
  kPokeStatusCommon = 96, // Misc summary screen icons (markings, ...)
  kTimeIcon = 97, // Loading wheel layout
  kMenuCursor = 98, // Red corner frame cursor layout
  kPoffinIcon = 99,
  kPokemonVoice = 100, // Cries and PR video audio
  kAmieModel = 101, // Poképuff models
  kBoutiqueData = 102, // Lighting + environment for boutique
  kBox = 103,
  kPokeballModel = 104, // Low-poly overworld Poké Ball models
  kPokeballModelBattle = 105, // High-poly battle Poké Ball models
  kStarterSelect = 106,
  kShop = 107, // Field Poké Mart shopping layouts
  kPlayerIcon = 108,
  kTrainerCard = 109, // Includes trainer card 3D camera
  kTouchBarCommon = 110, // Pokedex/Box lower touch bar
  kPcMenu = 111, // PC startup screen layouts
  kTradeList = 112, // Trading UI layouts
  kLinkBattleMenu = 113,
  kSuperTraining = 114,
  kSuperTrainingActorData = 115,
  kSuperTrainingAnimationData = 116,
  kSuperTrainingStageData = 117,
  kSuperTrainingBossData = 118,
  kSuperTrainingMookData = 119,
  kSuperTrainingBossAction = 120,
  kSuperTrainingMookAction = 121,
  kSuperTrainingBossAi = 122,
  kSuperTrainingMookAi = 123,
  kSuperTrainingMissileData = 124,
  kSuperTrainingFireData = 125,
  kSuperTrainingBulletData = 126,
  kSuperTrainingGoodsData = 127,
  kSuperTrainingItemData = 128,
  kSuperTrainingParticle = 129,
  kSuperTrainingParam = 130,
  kEvolutionDemo = 131,
  kPokedexData = 132,
  kTrainerModel = 133, // High-poly trainer battle models
  kCommonDisplay = 134, // Two-option common menu (e.g. move learning)
  kTrainerMessageData = 135,
  kBattleBackground = 136,
  kAreaObjectList = 137, // NPC registries
  kGts = 138,
  kHoloCasterMailData = 139,
  kHoloCasterMail = 140, // Holo-caster UI + models
  kOPower = 141, // Assist power UI
  kBoxSearch = 142,
  kGymGimmickSequence = 143,
  kAmieApp = 144, // Amie "rearrange room" scripts
  kAmieBackground = 145,
  kAmiePokepuff = 146,
  kItemShortcutButton = 147,
  kMoveRelearner = 148, // Move Reminder UI
  kPoffinCase = 149,
  kCaptureDemo = 150, // Capture tutorial cursor graphics
  kPokemonRide = 151, // Skiddo/Gogoat/Rhyhorn riding animations
  kCutsceneData = 152,
  kDialogueListMenu = 153, // Dialogue choice list layout
  kFormChangeEffect = 154,
  kMysteryGiftLayout = 155,
  kMysteryGiftEffect = 156, // Opening particle effect
  kGameSyncLayout = 157,
  kHoloCasterShader = 158, // Static noise mask
  kDialogCommon = 159, // Chatbox layout
  kTrainerTexture = 160, // Trainer mugshot images
  kBattleMatch = 161, // Online battle match layout
  kCutsceneSequence = 162,
  kHmCutEffect = 163,
  kHmRockSmashEffect = 164,
  kHmRockSmashWallEffect = 165, // Victory Road wall variant
  kHmDigEffect = 166,
  kFont = 167,
  kFriendEntry = 168, // Friend Safari friend list entry layout
  kFieldNonStayAnimation = 169,
  kRegulation = 170,
  kBattleVideoSave = 171, // VS Recorder graphics
  kGrammar = 172, // Language-specific article tables
  kTrialDownloadLayout = 173,
  kSortString = 174, // Table for sorting clothing/items/etc
  kH3dCommonShader = 175,
  kFieldResident = 176,
  kCommunicationWait = 177,
  kScrollBar = 178,
  kFriendSafariSelect = 179,
  kGameResidentGraphics = 180,
  kPokedexDistribution = 181,
  kBattleMaisonMovesets = 182, // Normal difficulty
  kBattleMaisonTrainerData = 183, // Normal difficulty
  kSuperMaisonMovesets = 184, // Super difficulty
  kSuperMaisonTrainerData = 185, // Super difficulty
  kInverseBattleMovesets = 186,
  kHallOfFamePc = 187, // Records layout
  kHomeButtonLock = 188,
  kMoveTable = 189, // Move stats
  kEggMove = 190,
  kLevelUpMove = 191,
  kEvolutionTable = 192,
  kMegaEvolutionTable = 193,
  kGrowthTable = 194, // XP level tables
  kPersonal = 195,
  kEggSpeciesTable = 196, // Offspring map
  kItemData = 197,
  kItemBattlePocket = 198,
  kBattleVideoPlayer = 199,
  kCommendation = 200, // Pokedex completion certificate
  kLanguageSelect = 201,
  kNumberInput = 202,
  kPhotoViewer = 203,
  kEshop = 204, // Gift download layouts
  kTrialHouseResult = 205,
  kWonderTrade = 206, // Miracle Trade
  kVsDemo = 207, // Pre/post battle sequence layout
  kBattleMaisonSelect = 208, // NPC/friend selection layout
  kPokemonCenter = 209, // Indoors model
  kFieldSubMotion = 210,
  kHmWaterfallSplash = 211,
  kGraphicFontCommon = 212, // Type/status effect icons, etc
  kGraphicFontBattle = 213, // Buttons and EXP bar
  kGraphicFontBattleEffect = 214, // "VS <Name>" intro texts
  kGraphicFontMisc = 215,
  kGraphicFontAmie = 216,
  kGraphicFontSuperTraining = 217,
  kFieldCommonSequence = 218,
  kLiveCup = 219,
  kBoutiqueEffect = 220, // Kisekae reveal preview effect
  kFishingEffect = 221, // Water splash
  kAmieGoodsData = 222,
  kAmieCakeData = 223,
  kLowerScreenTutorial = 224, // Unused
  kGraphicFontTutorial = 225, // Amie/Super Training tutorials
  kBattlePartySelect = 226,
  kSystemIcon = 227, // StreetPass box / extended save icons
  kBattleVideoPlay = 228, // VS Recorder player lower screen
  kStaffRoll = 229, // Credits layout
  kStaffRollData = 230,
  kStereoFrame = 231, // Stereoscopic black frame
  kGameOver = 232,
  kEncounterEffect = 233,
  kGraphicFontGameSync = 234,
  kGraphicFontPokedex = 235,
  kGraphicFontTheEnd = 236, // "Fin" text for credits
  kHallOfFameDemo = 237, // Cutscene layout + models
  kFatalError = 238,
  kGraphicFontNameInput = 239,
  kGraphicFontHallOfFameDemo = 240,
  kGameClearFade = 241, // Whiteout on finishing the game
  kContestData = 242,
  kPokeNavi = 243, // "PMN" lower screen app
  kGraphicFontPokeNavi = 244,
  kPokeNaviCommon = 245,
  kTvNavi = 246,
  kMapNavi = 247,
  kCaptureNavi = 248,
  kPlayNavi = 249,
  kContestAppealUi = 250, // Second-round appeal judging UI
  kSkyTripField = 251, // Latias/Latios flying
  kSkyTripOther = 252,
  kSkyTripEffect = 253,
  kSkyTripCharacter = 254, // Player + Latias/Latios flying models
  kSkyTripLayout = 255,
  kPokedexUi = 256,
  kSecretBase = 257, // Interior models
  kSecretBaseLayout = 258, // Lower screen
  kSecretBasePhoto = 259,
  kGymElectric = 260,
  kGymPsychic = 261, // Gimmick model
  kPokedexNaviData = 262,
  kPokemonPicture = 263, // Contest images
  kContestEffect = 264,
  kContestPhoto = 265,
  kGymFlying = 266,
  kContactEncounter = 267, // Overworld touch-encounter models
  kContactEncounterData = 268,
  kIntroMovie = 269,
  kAreaRoute102 = 270,
  kGymFighting = 271,
  kGymFire = 272,
  kGymWater = 273,
  kEliteFour = 274, // Room models
  kHallOfFameRoom = 275,
  kGraphicFontTouchBar = 276,
  kPokemonSpriteRs = 277, // AGB Ruby/Sapphire Pokedex sprites
  kGraphicFontContestDebut = 278,
  kGraphicFontContestAppeal = 279,
  kGraphicFontContestResult = 280,
  kAreaRoute120 = 281, // Water reflection resource
  kFieldScreenEffect = 282, // Flash HM effect
  kContestCamera = 283,
  kAreaWorld03 = 284, // Route 104/105 contact-encounter resource
  kAreaWorld05 = 285, // Route 104/105 contact-encounter resource
  kAreaRoute114 = 286,
  kAreaRoute124 = 287,
  kAreaUnderwater01 = 288,
  kAreaUnderwater02 = 289,
  kAreaUnderwater03 = 290,
  kHmFlyModel = 291, // Bird model + animations
  kAreaC105 = 292,
  kChampionPassage = 293,
  kSecretBaseQr = 294,
  kAreaT107 = 295,
  kAreaC108 = 296, // Water reflection resource
  kAreaD111 = 297,
  kMotionBlur = 298,
};
