/*
 * Copyright (C) 2026  David Darras
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

/** * @name Graphics & Rendering Addresses
 * @{ */
#define ADDRESS_GRAPHICS_GET_FRAMEBUFFER (0x0012FA94)
#define ADDRESS_GRAPHICS_BIND_FRAMEBUFFER (0x003717E0)
#define ADDRESS_GRAPHICS_ENABLE_SCISSOR (0x003A30A8)
#define ADDRESS_GRAPHICS_DISABLE_SCISSOR (0x003A3284)
#define ADDRESS_GRAPHICS_BEGIN_RENDER (0x00175A58)
#define ADDRESS_GRAPHICS_SET_TEXT_SCALE (0x003A3498)
#define ADDRESS_GRAPHICS_DRAW_TEXT (0x003A44C4)
#define ADDRESS_GRAPHICS_DRAW_RECT (0x00175BDC)
#define ADDRESS_STEREO_CAMERA_UPDATE_MATRICES (0x00377C10)
#define ADDRESS_STEREO_CAMERA_UPDATE_LOOK_AT (0x001483DC)
#define ADDRESS_STEREO_CAMERA_SET_PROJECTION_MATRIX (0x003939CC)
#define ADDRESS_MODEL_PLAY_ANIMATION (0x003FB1B4)
#define ADDRESS_RENDERER_CHANGE_OUTLINE_SCALE (0x00379E3C)
#define ADDRESS_RENDERER_CHANGE_OUTLINE_COLOR (0x00379C7C)
#define ADDRESS_RENDERER_CHANGE_AMBIENT_LIGHT_COLOR (0x00139710)
#define ADDRESS_RENDERER_CHANGE_DIFFUSE_LIGHT_COLOR (0x001397C0)
#define ADDRESS_RENDERER_DRAW_PICTURE (0x004BE3DC)
#define ADDRESS_RENDERER_DRAW_TEXT_BOX (0x00326FB8)
#define ADDRESS_APP_STATUS_SETUP_GRAPHICS_PARAMS (0x07144FC)
#define ADDRESS_APP_STATUS_SETUP_GRAPHICS_MOVES (0x70DDC0)
#define ADDRESS_APP_STATUS_SETUP_GRAPHICS_CONTEST (0x70D3D4)
#define ADDRESS_APP_STATUS_SETUP_GRAPHICS_INFOS (0x7116E4)
#define ADDRESS_H3DMODEL_GET_MATERIAL_COUNT             0x004CD168
#define ADDRESS_H3DMODEL_SET_COMBINER_COMBINE_RGB       0x00399920
#define ADDRESS_H3DMODEL_SET_COMBINER_SCALE_RGB         0x003997AC
#define ADDRESS_H3DMODEL_SET_COMBINER_SOURCE_RGB        0x00399880
#define ADDRESS_H3DMODEL_SET_COMBINER_OPERAND_RGB       0x0039994C
#define ADDRESS_H3DMODEL_SET_COMBINER_CONSTANT          0x003996FC
#define ADDRESS_H3DMODEL_SET_COLOR_CONSTANT             0x003988C8
#define ADDRESS_H3DMODEL_SET_MESH_VISIBLE               0x0039694C
#define ADDRESS_H3DMODEL_SET_COMBINER_COMBINE_ALPHA    0x00399C44
#define ADDRESS_H3DMODEL_SET_COMBINER_SOURCE_ALPHA     0x00399A94
#define ADDRESS_H3DMODEL_SET_COMBINER_OPERAND_ALPHA    0x00399C70
#define ADDRESS_H3DMODEL_SET_TRANSLUCENCY_KIND         0x00398C7C
#define ADDRESS_H3DMODEL_SET_ALPHA_TEST_ENABLE         0x00398BB4
/** @} */
